### ISSUE TITLE
Modifying AST tree

### ISSUE THREAD

**Issue by djn3m0** [Kronuz/esprima-python#2]
Hello,

I need to be able to walk over the tree, change some values and finally save the fixed tree. Im not sure if that is already possible with this project or not?

Thanks

**Comment by Kronuz** [comment]
Depending on the use case, you can change the nodes while they're being produced using `delegate, or produce a new tree after it's completely paraded while visiting each node using a `Visitor`.

**Comment by djn3m0** [comment]
My final goal is to modify the tree and finally generate .js file.
I have already tried to create a new tree while visiting each node using a Visitor, but it seems i cannot generate .js file using esgenerate from it! 
What do you propose for modifying a tree and generating .js file out of it?

thanks

**Comment by Kronuz** [comment]
There shouldn't be anything special about it. If you are forming a valid tree that's it. What are the changes you are making?

**Comment by djn3m0** [comment]
How can I form a valid tree? the visitor going over each node that is the only access i have to the tree. I dont know how I can form a valid tree from node returned from the visitor?

**Comment by Kronuz** [comment]
There's an example here: https://github.com/Kronuz/esprima-python/blob/master/examples/visitor.py
